# Generated by Django 4.2.5 on 2023-09-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование груза', max_length=200)),
                ('length', models.IntegerField(help_text='Длина (мм)')),
                ('width', models.IntegerField(help_text='Ширина (мм)')),
                ('height', models.IntegerField(help_text='Высота (мм)')),
                ('weight', models.FloatField(help_text='Вес (кг)')),
                ('amount', models.IntegerField(help_text='Количество (шт)')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
