# Generated by Django 4.2.5 on 2023-09-09 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование вагона', max_length=200)),
                ('floor_length', models.IntegerField(help_text='Длина пола (мм)')),
                ('floor_width', models.IntegerField(help_text='Ширина пола (мм)')),
                ('weight', models.FloatField(help_text='Масса тары (т)')),
                ('height_from_rails', models.IntegerField(help_text='Высота пола от УГР (мм)')),
                ('cg_height_from_rails', models.IntegerField(help_text='Высота центра тяжести от УГР (мм)')),
                ('base_length', models.IntegerField(help_text='База платформы (мм)')),
                ('s_side_surface_meters', models.FloatField(help_text='Площадь наветренной поверхности вагона (м²)')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование заказа', max_length=200)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('carriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.carriage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование груза', max_length=200)),
                ('length', models.IntegerField(help_text='Длина (мм)')),
                ('width', models.IntegerField(help_text='Ширина (мм)')),
                ('height', models.IntegerField(help_text='Высота (мм)')),
                ('weight', models.FloatField(help_text='Вес (кг)')),
                ('amount', models.IntegerField(default=1, help_text='Количество (шт)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
