# Generated by Django 4.2.5 on 2023-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование вагона', max_length=200)),
                ('floor_length', models.IntegerField(help_text='Длина пола (мм)')),
                ('floor_width', models.IntegerField(help_text='Ширина пола (мм)')),
                ('weight', models.FloatField(help_text='Масса тары (т)')),
                ('height_from_rails', models.IntegerField(help_text='Высота пола от УГР (мм)')),
                ('cg_height_from_rails', models.IntegerField(help_text='Высота центра тяжести от УГР (мм)')),
                ('base_length', models.IntegerField(help_text='База платформы (мм)')),
                ('s_side_surface_meters', models.FloatField(help_text='Площадь наветренной поверхности вагона (м²)')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='shipment',
            name='amount',
            field=models.IntegerField(default=1, help_text='Количество (шт)'),
        ),
    ]
