# Generated by Django 4.2.5 on 2023-09-09 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial_squashed_0003_order_shipment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='coords_of_cg',
            field=models.CharField(default='0,0,0', max_length=200, validators=[django.core.validators.int_list_validator]),
        ),
    ]
