# Generated by Django 4.2.5 on 2023-09-09 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_shipment_coords_of_cg'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calculation_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='carriage',
            field=models.ForeignKey(help_text='Тип вагона', on_delete=django.db.models.deletion.CASCADE, to='web_app.carriage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата создания заказа'),
        ),
    ]
